TrainingSystem/Models/TrainingStaff.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TrainingStaff
    {
        public int staffID { get; set; }

        [Required]
        [DisplayName("Username")]
        public string staff_username { get; set; }

        [Required]
        [DisplayName("Password")]
        public string staff_password { get; set; }

        [Required]
        [DisplayName("Fullname")]
        public string staff_fullname { get; set; }

        [DisplayName("Address")]
        public string staff_address { get; set; }

        [DisplayName("Email")]
        public string staff_email { get; set; }
    }
}

TrainingSystem/Controllers/EnrollController.cs
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingSystem.Models;

namespace TrainingSystem.Controllers
{
    public class EnrollController : Controller
    {
        private InternalTrainingSystemEntities db = new InternalTrainingSystemEntities();

        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "74UiAQSl7LINPN1eV2TWj7cDReSioM5YkzWRfPog",
            BasePath = "https://mvc-project-9443e-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;


        public ActionResult Index(int? page)
        {
            
            if (Session["Staff_UserName"] != null)
            {
                ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name");
                var enroll = db.Enroll.Include(a => a.Courses).Include(a => a.Trainee);
                return View(enroll.ToList().ToPagedList(page ?? 1, 20));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        [HttpPost]
        public ActionResult Index(int? courseID, int? page)
        {
                if (courseID != null)
                {
                    ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name");
                    var enroll = db.Enroll.Include(a => a.Courses).Include(a => a.Trainee).Where(a => a.courseID == courseID);
                    return View(enroll.ToList().ToPagedList(page ?? 1, 20));
                }
                else
                {
                    ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name");
                    var enroll = db.Enroll.Include(a => a.Courses).Include(a => a.Trainee);
                    return View(enroll.ToList().ToPagedList(page ?? 1, 20));
                }            

        }

   

        // GET: AssignCourse/Create
        public ActionResult Create()
        {
            if (Session["Staff_UserName"] != null)
            {
                ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name");       
                ViewBag.traineeID = new SelectList(db.Trainee, "traineeID", "trainee_username");
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }       

        }

        public JsonResult GetTrainee(int traineeID)
        {
            // Retrieve the course with the given ID from the database
            //var course = db.Courses.Where(c => c.courseID == courseID).ToList();

            var trainee = (from a in db.Trainee
                          where (traineeID == a.traineeID)
                          select new
                          {
                              trainee_fullname = a.trainee_fullname,
                              trainee_email = a.trainee_email
 
                          }).FirstOrDefault();

            return new JsonResult { Data = trainee, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

            // Return the result as JSON
            //return Json(course);
        }

        // POST: AssignCourse/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "enrollID,enroll_descriptions,courseID,traineeID,enroll_date")] Enroll enroll)
        {
            if (ModelState.IsValid)
            {
                var SearchData = db.Enroll.Where(x => x.courseID == enroll.courseID).Where
                                         (x => x.traineeID == enroll.traineeID).SingleOrDefault();

                if (SearchData != null)
                {
                    ViewBag.Status = "Already have enrolled";
                }
                else
                {
                    db.Enroll.Add(enroll);
                    db.SaveChanges();

                    try
                    {
                        AddEnrollToFirebase(enroll);
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError(string.Empty, ex.Message);
                    }

                    ViewBag.Message = "Create successfully";
                }
            }

            ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name", enroll.courseID);
            ViewBag.traineeID = new SelectList(db.Trainee, "traineeID", "trainee_username", enroll.traineeID);
            return View(enroll);
        }

        // GET: AssignCourse/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Staff_UserName"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Enroll enroll = db.Enroll.Find(id);
                if (enroll == null)
                {
                    return HttpNotFound();
                }
                ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name", enroll.courseID);
                ViewBag.traineeID = new SelectList(db.Trainee, "traineeID", "trainee_username", enroll.traineeID);
                return View(enroll);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            

        }

        // POST: AssignCourse/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "enrollID,enroll_descriptions,courseID,traineeID,enroll_date")] Enroll enroll)
        {
            if (ModelState.IsValid)
            {
                var SearchData = db.Enroll.Where(x => x.enrollID != enroll.enrollID && x.courseID == enroll.courseID).Where
                                         (x => x.traineeID == enroll.traineeID).SingleOrDefault();

                if (SearchData != null)
                {
                    ViewBag.Status = "Already have enrolled";
                }
                else
                {
                    db.Entry(enroll).State = EntityState.Modified;
                    db.SaveChanges();
                    client = new FireSharp.FirebaseClient(config);
                    var data = enroll;
                    SetResponse setResponse = client.Set("Enroll/" + enroll.enrollID, data);
                    ViewBag.Message = "Edit successfully";
                }


            }
            ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name", enroll.courseID);
            ViewBag.traineeID = new SelectList(db.Trainee, "traineeID", "trainee_username", enroll.traineeID);
            return View(enroll);
        }

        // GET: AssignCourse/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Staff_UserName"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Enroll enroll = db.Enroll.Find(id);
                if (enroll == null)
                {
                    return HttpNotFound();
                }
                return View(enroll);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            

        }

        // POST: AssignCourse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enroll enroll = db.Enroll.Find(id);
            db.Enroll.Remove(enroll);
            db.SaveChanges();
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Delete("Enroll/" + id);
            return RedirectToAction("Index");
        }



        private void AddEnrollToFirebase(Enroll enroll)
        {
            client = new FireSharp.FirebaseClient(config);
            var data = enroll;

            PushResponse response = client.Push("Enroll/" + enroll.enrollID, data);
            //SetResponse setResponse = client.Set("Courses/", data);
        }
    }
}

TrainingSystem/Controllers/TopicController.cs
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingSystem.Models;

namespace TrainingSystem.Controllers
{
    public class TopicController : Controller
    {
        private InternalTrainingSystemEntities db = new InternalTrainingSystemEntities();

        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "74UiAQSl7LINPN1eV2TWj7cDReSioM5YkzWRfPog",
            BasePath = "https://mvc-project-9443e-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;

        // GET: Topic
        public ActionResult Index(int? page)
        {
            var topic = db.Topic.Include(t => t.Courses);
            
            return View(topic.ToList().ToPagedList(page ?? 1, 20));

        }


        // GET: Topic/Create
        public ActionResult Create()
        {
            if (Session["Staff_Username"] != null)
            {
                ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name");
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        // POST: Topic/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "topicID,topic_name,topic_descriptions,courseID,course_time, topic_status")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Topic.Add(topic);
                db.SaveChanges();

                try
                {
                    AddTopicToFirebase(topic);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
                ViewBag.Message = "Create successfully";
            }

            ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name", topic.courseID);
            return View(topic);
        }

        // GET: Topic/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Staff_Username"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Topic topic = db.Topic.Find(id);
                if (topic == null)
                {
                    return HttpNotFound();
                }
                ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name", topic.courseID);
                return View(topic);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        // POST: Topic/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "topicID,topic_name,topic_descriptions,courseID,course_time, topic_status")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();

                client = new FireSharp.FirebaseClient(config);
                var data = topic;
                SetResponse setResponse = client.Set("Topic/" + topic.topicID, data);

                ViewBag.Message = "Edit successfully";
            }
            ViewBag.courseID = new SelectList(db.Courses, "courseID", "course_name", topic.courseID);
            return View(topic);
        }

        // GET: Topic/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Staff_Username"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Topic topic = db.Topic.Find(id);
                if (topic == null)
                {
                    return HttpNotFound();
                }
                return View(topic);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Topic/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Topic topic = db.Topic.Find(id);
                db.Topic.Remove(topic);
                db.SaveChanges();

                client = new FireSharp.FirebaseClient(config);
                FirebaseResponse response = client.Delete("Topic/" + id);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        private void AddTopicToFirebase(Topic topic)
        {
            client = new FireSharp.FirebaseClient(config);
            var data = topic;

            PushResponse response = client.Push("Topic/" + topic.topicID, data);
        }
    }
}

TrainingSystem/Views/TrainingStaff/ChangePassword.cshtml
@{
    ViewBag.Title = "ChangePassword";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h2>Update Profile</h2>
                <ul class="breadcrumb">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Update Profile", "UpdateProfile", "TrainingStaff")</li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            @Html.ActionLink("Back", "StaffDashBoard", null, new { @class = "btn btn-success" })

        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                <div class="form-horizontal">
                    @*<h3 style="padding-top: 10px">Change Password</h3> <hr />*@
                    @*<div class="form-group">
                            @Html.Label("Input Old Password", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Password("old_password", null, new { @class = "form-control" }) <br />
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Input New Password", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Password("new_password", null, new { @class = "form-control" }) <br />
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Input Confirm New Password", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.Password("confirm_password", null, new { @class = "form-control" }) <br /> <br />
                            </div>
                        </div>*@

                    @Html.Label("Input Old Password", new { @class = "control-label col-md-2" })
                    @Html.Password("old_password", null, new { @class = "form-control" }) <br />
                    @Html.Label("Input New Password", new { @class = "control-label col-md-2" })
                    @Html.Password("new_password", null, new { @class = "form-control" }) <br />
                    @Html.Label("Input Confirm New Password", new { @class = "control-label col-md-2" })
                    @Html.Password("confirm_password", null, new { @class = "form-control" }) <br /> <br />
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Change Password" class="btn btn-primary" /> <br /><br />
                        
                    </div>

                    <h5 class="text-danger">@ViewData["Message"]</h5>
                </div>
            }
        </div>
    </div>
</div>

TrainingSystem/Views/TrainingStaff/Create.cshtml
@model TrainingSystem.Models.TrainingStaff
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h2>Add Training Staff</h2>
                <ul class="breadcrumb">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Add Training Staff", "Create", "TrainingStaff")</li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })

        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.staff_username, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.staff_username, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.staff_username, "", new { @class = "text-danger" })
                            <h5 class="text-danger">@ViewBag.Status</h5>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.staff_password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.staff_password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                            @Html.ValidationMessageFor(model => model.staff_password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.staff_fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.staff_fullname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.staff_fullname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.staff_address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.staff_address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.staff_address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.staff_email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.staff_email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.staff_email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>

                    @if (ViewBag.Message != null)
                    {
                        <div class="alert alert-success alert-dismissible" role="alert">
                            <strong>@ViewBag.Message</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

TrainingSystem/Views/TrainingStaff/Delete.cshtml
@model TrainingSystem.Models.TrainingStaff
@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h2>Delete Trainer</h2>
                <ul class="breadcrumb">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Detele Trainer", "Delete", "Trainer")</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })

        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-9">
                        <div class="col-md-12">
                            <h3>Trainer Information</h3>
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.staff_username)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.staff_username)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.staff_fullname)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.staff_fullname)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.staff_address)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.staff_address)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.staff_email)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.staff_email)
                                </dd>

                            </dl>

                            <h4>Are you sure you want to delete this?</h4>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Delete" class="btn btn-danger" />
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TrainingSystem/Views/TrainingStaff/StaffDashBoard.cshtml
@{
    ViewBag.Title = "StaffDashBoard";
    /*Layout = "~/Views/Shared/_Layout1.cshtml";*/
}

<!--<h2 class="w3-text-teal">Staff DashBoard</h2>
<div class="list-group">
    <ul style="font-size: 20px; list-style-image: url('../../Images/rocket.png')">
        <li>
            @Html.ActionLink("Change Password", "ChangePassword", "TrainingStaff")
        </li>
        <li>
            @Html.ActionLink("Update Profile", "UpdateProfile", "TrainingStaff")
        </li>
        <li>
            @Html.ActionLink("Manage Trainer ", "Index", "Trainer")
        </li>
        <li>
            @Html.ActionLink("Manage Trainee", "Index", "Trainee")
        </li>
        <li>
            @Html.ActionLink("Manage Course", "Index", "Courses")
        </li>
        <li>
            @Html.ActionLink("Manage Course Categories", "Index", "CourseCategories")
        </li>
        <li>
            @Html.ActionLink("Manage Enroll", "Index", "Enroll")
        </li>
        <li>
            @Html.ActionLink("Manage Assign Course", "Index", "AssignCourse")
        </li>
    </ul>
</div>
    -->

<section id="mu-page-breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mu-page-breadcrumb-area">
                    <h2>Training Staff</h2>
                    <ol class="breadcrumb">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="active">@Html.ActionLink("Staff Dashboard", "StaffDashBoard", "TrainingStaff")</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>


<section id="mu-course-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mu-course-content-area">
                    <div class="mu-course-container mu-course-details">
                            <div class="col-md-4">
                                <div class="mu-contact-left">
                                    <img src="~/Images/study.jpg" width="100%" height="450" frameborder="0" style="border:0">
                                </div>
                            </div>
                            <div class="col-md-1">

                            </div>
                            <div class="col-md-6 col-lg-6">
                                <div class="mu-contact-right">
                                    <div class="mu-latest-course-single-content">
                                        <h3>Manage Account</h3>
                                        <hr />
                                        <ul style="font-size: 20px; list-style-image: url('../../Images/rocket.png')">
                                            <li>
                                                @Html.ActionLink("Change Password", "ChangePassword", "TrainingStaff")
                                            </li>
                                            <li>
                                                @Html.ActionLink("Update Profile", "UpdateProfile", "TrainingStaff")
                                            </li>
                                        </ul>
                                        
                                        <h3>Manage Course</h3>
                                        <hr />
                                        <ul style="font-size: 20px; list-style-image: url('../../Images/rocket.png')">
                                            <li>
                                                @Html.ActionLink("Manage Course", "Index", "Courses")
                                            </li>
                                            <li>
                                                @Html.ActionLink("Manage Course Categories", "Index", "CourseCategories")
                                            </li>
                                            <li>
                                                @Html.ActionLink("Manage Assign Course", "Index", "AssignCourse")
                                            </li>

                                            <li>
                                                @Html.ActionLink("Manage Enroll", "Index", "Enroll")
                                            </li>

                                            <li>
                                                @Html.ActionLink("Manage Topic", "Index", "Topic")
                                            </li>

                                            <li>
                                                @Html.ActionLink("Manage Schedule", "Index", "Events")
                                            </li>

                                            <li>
                                                @Html.ActionLink("Manage Request", "Index", "Request")
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
</section>