TrainingSystem/Controllers/RequestController.cs
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingSystem.Models;

namespace TrainingSystem.Controllers
{
    public class RequestController : Controller
    {
        private InternalTrainingSystemEntities db = new InternalTrainingSystemEntities();

        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "74UiAQSl7LINPN1eV2TWj7cDReSioM5YkzWRfPog",
            BasePath = "https://mvc-project-9443e-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;

        // GET: Request
        public ActionResult Index(int? page)
        {
           
            if (Session["Staff_UserName"] != null)
            {

                var request = db.Request.Include(t => t.Trainer);
                return View(request.ToList().ToPagedList(page ?? 1, 20));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult ShowRequest()
        {
       
            if (Session["Trainer_UserName"] != null)
            {

                //var request = db.Request.Include(t => t.Trainer);

                int user = Convert.ToInt32(Session["ID"]);

                var request = (from a in db.Request
                                   join c in db.Trainer on a.trainerID equals c.trainerID
                                   where (a.trainerID == user)
                                   select a).OrderByDescending(a=> a.request_date).DefaultIfEmpty();

                return View(request.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Topic/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Staff_Username"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Request request = db.Request.Find(id);
                if (request == null)
                {
                    return HttpNotFound();
                }
                return View(request);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        // GET: Topic/Create
        public ActionResult Create()
        {
            if (Session["Trainer_Username"] != null)
            {
                
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        // POST: Topic/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "requestID,request_subject,request_descriptions,trainerID,request_answer,request_date, request_status")] Request request)
        {
            if (ModelState.IsValid)
            {
                int trainerID = Convert.ToInt32(Session["ID"]);
                request.trainerID = trainerID;
                db.Request.Add(request);
                db.SaveChanges();

                try
                {
                    AddRequestToFirebase(request);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }

                ViewBag.Message = "Create successfully";
            }

            return View(request);
        }

        // GET: Topic/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Staff_Username"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Request request = db.Request.Find(id);
                var status = new List<string>() { "Approved", "Denied", "Waiting" };
                ViewBag.status = status;
                if (request == null)
                {
                    return HttpNotFound();
                }
                return View(request);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        // POST: Topic/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "requestID,request_subject,request_descriptions,request_answer,trainerID,request_date, request_status")] Request request)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(request).State = EntityState.Modified;
                db.SaveChanges();

                client = new FireSharp.FirebaseClient(config);
                var data = request;
                SetResponse setResponse = client.Set("Request/" + request.requestID, data);

                ViewBag.Message = "Edit successfully";
            }

            var status = new List<string>() { "Approved", "Denied", "Waiting" };
            ViewBag.status = status;
            return View(request);
        }

        // GET: Topic/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Staff_Username"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Request request = db.Request.Find(id);
                if (request == null)
                {
                    return HttpNotFound();
                }
                return View(request);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Topic/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Request request = db.Request.Find(id);
                db.Request.Remove(request);
                db.SaveChanges();

                client = new FireSharp.FirebaseClient(config);
                FirebaseResponse response = client.Delete("Request/" + id);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }

        private void AddRequestToFirebase(Request request)
        {
            client = new FireSharp.FirebaseClient(config);
            var data = request;

            PushResponse response = client.Push("Request/" + request.requestID, data);
        }
    }
}

TrainingSystem/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingSystem.Models;
using PagedList.Mvc;
using PagedList;
using System.Dynamic;
using FireSharp.Interfaces;
using FireSharp.Config;
using FireSharp.Response;


namespace TrainingSystem.Controllers
{
    public class TrainerController : Controller
    {
        private InternalTrainingSystemEntities db = new InternalTrainingSystemEntities();

        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "74UiAQSl7LINPN1eV2TWj7cDReSioM5YkzWRfPog",
            BasePath = "https://mvc-project-9443e-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;

        // GET: Trainer
        public ActionResult Index(int? page)
        {
            if (Session["Admin_UserName"] != null)
            {
                return View(db.Trainer.ToList().ToPagedList(page ?? 1, 20));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Trainer trainer)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                var obj = db.Trainer.Where(a => a.trainer_username.Equals(trainer.trainer_username) &&
                                     a.trainer_password.Equals(trainer.trainer_password)).FirstOrDefault();
                if (obj != null)
                {
                    Session["TrainerID"] = obj.trainerID.ToString();
                    Session["Trainer_UserName"] = obj.trainer_username.ToString();
                    return RedirectToAction("TrainerDashBoard");
                }
            }
            return View(trainer);
        }

        public ActionResult TrainerDashBoard()
        {
            if (Session["Trainer_UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        // GET: Trainer/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Staff_UserName"] != null || Session["Admin_UserName"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Trainer trainer = db.Trainer.Find(id);

                ViewBag.AssignCourse = (from a in db.AssignCourse
                               join c in db.Trainer on a.trainerID equals c.trainerID
                               join d in db.Courses on a.courseID equals d.courseID
                               where (c.trainerID == id)
                               select a).ToList();

                if (trainer == null)
                {
                    return HttpNotFound();
                }
                return View(trainer);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            


        }

        // GET: Trainer/Create
        public ActionResult Create()
        {

            if (Session["Admin_UserName"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            

        }

        // POST: Trainer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "trainerID,trainer_username,trainer_password,trainer_fullname,trainer_address,trainer_workingplace,trainer_phone,trainer_email")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                var SearchData = db.Trainer.Where(x => x.trainer_username == trainer.trainer_username).SingleOrDefault();

                if (SearchData != null)
                {
                    ViewBag.Status = "Account not available";
                }

                else
                {
                    db.Trainer.Add(trainer);
                    db.SaveChanges();

                    try
                    {
                        AddTrainerToFirebase(trainer);
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError(string.Empty, ex.Message);
                    }
                    ViewBag.Message = "Create successfully";
                }
            }

            return View(trainer);
        }

        // GET: Trainer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Admin_UserName"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Trainer trainer = db.Trainer.Find(id);
                if (trainer == null)
                {
                    return HttpNotFound();
                }
                return View(trainer);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }
        // POST: Trainer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "trainerID,trainer_username,trainer_password,trainer_fullname,trainer_address,trainer_workingplace,trainer_phone,trainer_email")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainer).State = EntityState.Modified;
                db.SaveChanges();

                client = new FireSharp.FirebaseClient(config);
                var data = trainer;
                SetResponse setResponse = client.Set("Trainer/" + trainer.trainerID, data);

                ViewBag.Message = "Edit successfully";
            }
            return View(trainer);
        }


        // GET: Trainer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["Admin_UserName"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Trainer trainer = db.Trainer.Find(id);
                if (trainer == null)
                {
                    return HttpNotFound();
                }
                return View(trainer);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Trainer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trainer trainer = db.Trainer.Find(id);
            db.Trainer.Remove(trainer);
            db.SaveChanges();

            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Delete("Trainer/" + id);

            return RedirectToAction("Index");
        }

        public ActionResult ChangePassword()
        {
            if (Session["Trainer_Username"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult ChangePassword(string old_password, string new_password, string confirm_password)
        {
            string trainer_username = Session["Trainer_Username"].ToString();
            var obj = db.Trainer.Where(a => a.trainer_username.Equals(trainer_username) &&
                                     a.trainer_password.Equals(old_password)).FirstOrDefault();
            if (obj != null)
            {
                if (new_password.Equals(confirm_password))
                {
                    obj.trainer_password = new_password;
                    db.SaveChanges();

                    return RedirectToAction("TrainerDashBoard");
                }
            }
            ViewData["Message"] = "Old password is not correct or New password and " + "Confirm New Password are not match";
            return View();
        }

        public ActionResult UpdateProfile()
        {
            int trainerID = Convert.ToInt32(Session["ID"]);
            if (trainerID == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(db.Trainer.Find(trainerID));

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateProfile([Bind(Include = "trainerID,trainer_username,trainer_password,trainer_fullname,trainer_address,trainer_workingplace,trainer_phone,trainer_email")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainer).State = EntityState.Modified;
                db.SaveChanges();

                client = new FireSharp.FirebaseClient(config);
                var data = trainer;
                SetResponse setResponse = client.Set("Trainer/" + trainer.trainerID, data);

                return RedirectToAction("TrainerDashBoard");
            }
            return View(trainer);
        }

        public ActionResult Logout()
        {
            Session.Clear();  //remove all sessions in your app

TrainingSystem/Views/Trainer/Create.cshtml
@model TrainingSystem.Models.Trainer

@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h2>Add Trainer</h2>
                <ul class="breadcrumb">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Add Trainer", "Create", "Trainer")</li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })

        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.trainer_username, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.trainer_username, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.trainer_username, "", new { @class = "text-danger" })
                            <h5 class="text-danger">@ViewBag.Status</h5>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.trainer_password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.trainer_password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                            @Html.ValidationMessageFor(model => model.trainer_password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.trainer_fullname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.trainer_fullname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.trainer_fullname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.trainer_address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.trainer_address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.trainer_address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.trainer_workingplace, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.trainer_workingplace, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.trainer_workingplace, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.trainer_phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.trainer_phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.trainer_phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.trainer_email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.trainer_email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.trainer_email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>

                    @if (ViewBag.Message != null)
                    {
                        <div class="alert alert-success alert-dismissible" role="alert">
                            <strong>@ViewBag.Message</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

TrainingSystem/Views/Trainer/Delete.cshtml
@model TrainingSystem.Models.Trainer

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h2>Delete Trainer</h2>
                <ul class="breadcrumb">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Detele Trainer", "Delete", "Trainer")</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })

        </div>
        <div class="panel-body">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-9">
                        <div class="col-md-12">
                            <h3>Trainer Information</h3>

                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.trainer_username)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.trainer_username)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.trainer_fullname)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.trainer_fullname)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.trainer_address)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.trainer_address)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.trainer_workingplace)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.trainer_workingplace)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.trainer_phone)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.trainer_phone)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.trainer_email)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.trainer_email)
                                </dd>

                            </dl>

                            <h4>Are you sure you want to delete this?</h4>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Delete" class="btn btn-danger" />
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TrainingSystem/Views/Trainer/TrainerDashBoard.cshtml
@{
    ViewBag.Title = "TrainerDashBoard";
    //Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!--<div class="list-group">
    <ul style="font-size: 20px; list-style-image: url('../../Images/rocket.png')">
        <li>
            @Html.ActionLink("Change Password", "ChangePassword", "Trainer")
        </li>
        <li>
            @Html.ActionLink("Update Profile", "UpdateProfile", "Trainer")
        </li>
    </ul>
</div>-->

<section id="mu-page-breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mu-page-breadcrumb-area">
                    <h2>Trainer</h2>
                    <ol class="breadcrumb">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="active">@Html.ActionLink("Trainer Dashboard", "TrainerDashBoard", "Trainer")</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="mu-course-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mu-course-content-area">
                    <div class="mu-course-container mu-course-details">
                        <div class="col-md-4">
                            <div class="mu-contact-left">
                                <img src="~/Images/study.jpg" width="100%" height="450" frameborder="0" style="border:0">
                            </div>
                        </div>
                        <div class="col-md-1">

                        </div>
                        <div class="col-md-6 col-lg-6">
                            <div class="mu-contact-right">
                                <div class="mu-latest-course-single-content">
                                    <h3>Manage Account</h3>
                                    <ul style="font-size: 20px; list-style-image: url('../../Images/rocket.png')">
                                        <li>
                                            @Html.ActionLink("Change Password", "ChangePassword", "Trainer")
                                        </li>

                                        <li>
                                            @Html.ActionLink("Update Profile", "UpdateProfile", "Trainer")
                                        </li>
                                    </ul>
                                    <h3>View Information</h3>
                                    <ul style="font-size: 20px; list-style-image: url('../../Images/rocket.png')">

                                        <li>
                                            @Html.ActionLink("View Assign Course", "ShowAssignCourse", "AssignCourse")
                                        </li>

                                        <li>
                                            @Html.ActionLink("View Request", "ShowRequest", "Request")
                                        </li>

                                        <li>
                                            @Html.ActionLink("View Schedule", "ScheduleByUser", "Events")
                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>